apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # Defines the pods going to represent this Service
  # Service becomes a network endpoint for either other services
  # or mabye external users to connect to (eg browser)
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  # Defines the pods going to represent this Service
  # Service becomes a network endpoint for either other services
  # or mabye external users to connect to (eg browser)
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    -  name: endpoint
       port: 61616


  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  # Defines the pods going to represent this Service
  # Service becomes a network endpoint for either other services
  # or mabye external users to connect to (eg browser)
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  # Defines the pods going to represent this Service
  # Service becomes a network endpoint for either other services
  # or mabye external users to connect to (eg browser)
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

  type: ClusterIP


